# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0367ed0f0712cad994ca0c52f3e801ada5652886e1acdd96e8bdda1fece55b3dc407b2370dfd1696100fbd2d16693466b7433e9d6e6b54c57a5524e7e67f286

test:
  secret_key_base: c41732468aa64f6993f71db21ec413256fd64881a29f92a260882ab354be2a52204d3634a7b0459a11308bf8f3b634c5fdb8f4a1fb3c311439ff9028a221495d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
